export type Section = 'components' | 'catalog' | 'plugins'

export const FAMILIES: Record<Section, Record<string, readonly string[]>> = {
  components: {
    actions: ['qds-control-standard-button', 'qds-control-outline-button', 'qds-card-header-action'],
    identity: ['qds-badge-floating', 'qds-badge-multiline', 'qds-chip-square', 'qds-chip-avatar'],
    forms: [
      'qds-control-input',
      'qds-control-input-filled',
      'qds-control-input-error',
      'qds-control-select',
      'qds-control-select-multiple',
      'qds-field-float-value',
      'qds-field-start-form',
    ],
    data: ['qds-table-official-modes', 'qds-table-no-chrome', 'qds-pagination', 'qds-pagination-input', 'qds-flush-card-table'],
    tabs: ['qds-tabs-horizontal', 'qds-tabs-vertical', 'qds-tabs-scroll'],
  },
  catalog: {
    actions: [
      'qds-btn-dropdown',
      'qds-btn-group',
      'qds-btn-toggle',
      'qds-rating-active',
      'qds-rating-half',
      'qds-toolbar-surface',
      'qds-toolbar-dense',
      'qds-bar-standard',
      'qds-bar-dark',
      'qds-separator-inset-host',
    ],
    identity: [
      'qds-avatar',
      'qds-breadcrumbs',
      'qds-breadcrumbs-overflow',
      'qds-banner',
      'qds-banner-actions',
      'qds-banner-dense',
    ],
    tabs: ['qds-tab-panels'],
    forms: [
      'qds-catalog-input-error',
      'qds-catalog-select-multiple',
      'qds-catalog-option-group',
      'qds-catalog-checkbox',
      'qds-catalog-radio',
      'qds-catalog-toggle',
      'qds-catalog-file-multiple',
      'qds-catalog-file-progress',
      'qds-catalog-slider',
      'qds-catalog-range',
      'qds-catalog-color',
      'qds-catalog-date',
      'qds-catalog-date-range',
      'qds-catalog-time',
    ],
    data: [
      'qds-linear-progress',
      'qds-circular-progress',
      'qds-spinner',
      'qds-expansion-expanded',
      'qds-expansion-collapsed',
      'qds-expansion-dense',
      'qds-tree-primary',
      'qds-tree-dense',
    ],
    media: [
      'qds-stepper',
      'qds-stepper-vertical',
      'qds-stepper-horizontal',
      'qds-stepper-compact',
      'qds-timeline',
      'qds-timeline-dense',
      'qds-chat-sent',
      'qds-chat-received',
      'qds-carousel',
      'qds-scroll-area',
      'qds-splitter',
      'qds-slide-item',
      'qds-knob',
      'qds-editor',
      'qds-uploader',
    ],
  },
  plugins: {
    plugins: [
      'qds-plugin-bottomsheet-card',
      'qds-plugin-dialog-notify-card',
      'qds-plugin-loading-card',
      'qds-plugin-inner-loading-box',
      'qds-plugin-status-card',
    ],
  },
}
