/**
 * Canonical inventory of the public CSS custom-property contract.
 * Every `--qds-*` token the package emits is listed here so consumers can
 * discover, type, and override the full surface. The stable public contract
 * is the `--qds-*` prefix; Sass map names remain internal.
 */
export const QDS_TOKENS = [
  '--qds-color-primary',
  '--qds-color-primary-light',
  '--qds-color-primary-dark',
  '--qds-color-secondary',
  '--qds-color-accent',
  '--qds-color-positive',
  '--qds-color-negative',
  '--qds-color-warning',
  '--qds-color-info',
  '--qds-color-primary-rgb',
  '--qds-color-primary-light-rgb',
  '--qds-color-primary-dark-rgb',
  '--qds-color-secondary-rgb',
  '--qds-color-accent-rgb',
  '--qds-color-positive-rgb',
  '--qds-color-negative-rgb',
  '--qds-color-warning-rgb',
  '--qds-color-info-rgb',
  '--qds-surface-0',
  '--qds-surface-1',
  '--qds-surface-2',
  '--qds-surface-3',
  '--qds-surface-glass',
  '--qds-text',
  '--qds-text-strong',
  '--qds-text-muted',
  '--qds-border',
  '--qds-border-subtle',
  '--qds-space-xs',
  '--qds-space-sm',
  '--qds-space-md',
  '--qds-space-lg',
  '--qds-space-xl',
  '--qds-radius-xs',
  '--qds-radius-sm',
  '--qds-radius-md',
  '--qds-radius-lg',
  '--qds-radius-xl',
  '--qds-radius-full',
  '--qds-radius-control',
  '--qds-shadow-sm',
  '--qds-shadow-md',
  '--qds-shadow-lg',
  '--qds-elevation-1',
  '--qds-elevation-2',
  '--qds-elevation-3',
  '--qds-interactive-bg',
  '--qds-interactive-bg-hover',
  '--qds-interactive-bg-active',
  '--qds-interactive-border',
  '--qds-interactive-border-strong',
  '--qds-interactive-text',
  '--qds-interactive-text-muted',
  '--qds-font-family',
  '--qds-font-family-display',
  '--qds-font-family-accent',
  '--qds-font-weight-regular',
  '--qds-font-weight-medium',
  '--qds-font-weight-semibold',
  '--qds-font-weight-bold',
  '--qds-motion-fast',
  '--qds-motion-base',
  '--qds-focus-ring-width',
  '--qds-focus-ring-opacity',
  '--qds-focus-ring-offset',
  '--qds-motion-duration-fast',
  '--qds-motion-duration-base',
  '--qds-motion-ease-out',
  '--qds-motion-ease-in-out',
  '--qds-state-hover-opacity',
  '--qds-state-focus-opacity',
  '--qds-state-press-opacity',
  '--qds-tonal-bg-opacity',
  '--qds-tonal-hover-opacity',
  '--qds-tonal-border-opacity',
  '--qds-border-width-control',
  '--qds-control-letter-spacing',
  '--qds-control-text-transform',
  '--qds-control-content-line-height',
  '--qds-button-radius',
  '--qds-button-min-height',
  '--qds-button-padding-inline',
  '--qds-button-dense-min-height',
  '--qds-button-dense-padding-inline',
  '--qds-button-dense-radius',
  '--qds-button-dense-font-size',
  '--qds-button-round-size',
  '--qds-chip-radius',
  '--qds-badge-radius',
  '--qds-badge-min-height',
  '--qds-badge-padding',
  '--qds-field-focus-border-width',
  '--qds-glass-blur',
  '--qds-glass-saturate',
  '--qds-glass-border-mix',
  '--qds-card-bg',
  '--qds-card-border',
  '--qds-card-radius',
  '--qds-card-shadow',
  '--qds-menu-bg',
  '--qds-menu-border',
  '--qds-menu-radius',
  '--qds-menu-shadow',
  '--qds-notification-radius',
  '--qds-notification-shadow',
  '--qds-toolbar-bg',
] as const

/** A public CSS custom-property name in the `--qds-*` contract. */
export type QdsToken = (typeof QDS_TOKENS)[number]

/** A partial override map keyed by public token name. */
export type QdsTokenMap = Partial<Record<QdsToken, string>>
